server:
  port: 8088


spring:
 datasource:
    url: jdbc:mysql://localhost:3306/sakila?characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


 application:
    name: lilai

project:
   swagger:
          title: swageer 测试项目
          description: swageer Demo
          version: 0.0.1
          termsOfServiceUrl:
          contactName:
          contactUrl:
          contactEmail:
          license:
          licenseUrl: