server:
  port: 8088


spring:
 datasource:
    url: jdbc:mysql://localhost:3306/springdemo?characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
 data:
    elasticsearch:
#      cluster-name: docker-cluster
      cluster-nodes: 192.168.217.129:9300
      local: false
      repositories:
        enabled: true
 elasticsearch:
     rest:
       uris: ["http://192.168.217.129:9200"]

 application:
    name: lilai
 redis:
  host: 127.0.0.1
  port: 6379

#security:
#  basic:
#    enabled: false







project:
   swagger:
          title: swageer 测试项目
          description: swageer Demo
          version: 0.0.1
          termsOfServiceUrl:
          contactName:
          contactUrl:
          contactEmail:
          license:
          licenseUrl:


secretKey:  cifmedia
tokenValidityInSeconds: 86400000

