server:
  port: 8088


spring:
 datasource:
    url: jdbc:mysql://localhost:3306/springdemo?characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
 data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.217.128:9300
      local: false
      repositories:
        enabled: true


 application:
    name: lilai
 redis:
  host: 127.0.0.1
  port: 6379






project:
   swagger:
          title: swageer 测试项目
          description: swageer Demo
          version: 0.0.1
          termsOfServiceUrl:
          contactName:
          contactUrl:
          contactEmail:
          license:
          licenseUrl: